
name = "Bindingtests"
uuid = "1b08a953-4be3-4667-9a23-ab5d8c02c01c"
authors = ["Jay Leimer <jay@jinxx.eu>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
